In [1]:
import pandas as pd
non = pd.read_csv('Final_book_details_271.csv')
non2 = pd.read_csv('Final_book_details_272.csv')
non3 = pd.read_csv('Final_book_details_273.csv')
non4 = pd.read_csv('Final_book_details_274.csv')
non5 = pd.read_csv('Final_book_details_275.csv')
non5

/tmp/ipykernel_58703/1065816456.py:5: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  non4 = pd.read_csv('Final_book_details_274.csv')

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best
0,55364,부와 행운을 끌어당기는 우주의 법칙,"“ 무일푼, 무스펙에서 경제적 자유를 이룬젊은 부자 김도사 권마담 부부의성공과 부,...",자기계발,굿웰스북스,김태광(김도사),840.0,"18,000원",95076848.0,0,N
1,55365,우리는 책 읽는 가족입니다,"“독서, 이제는 온가족이 함께 하라!”행복한 가족을 만들고 싶다면 함께 독서하라!“...",자기계발,미다스북스(리틀미다스),정미숙,24.0,"15,000원",95076904.0,0,N
2,55366,1년에 200권 읽으면 일어나는 일,책을 읽는 방법을 바꾸자삶의 많은 것들이 바뀌기 시작했다!“책을 읽으면 대체 뭐가 ...,자기계발,미다스북스(리틀미다스),남영화,36.0,"15,000원",95077005.0,0,N
3,55367,우리 직업은 미래형이라서요,"모두가 프리랜서가 된다는 시대,여성 프리랜서로 무사히 살아남을 수 있을까모두가 프리...",에세이,이음,박초롱,24.0,"15,000원",95077067.0,0,N
4,55368,내가 처음 뇌를 열었을 때,선데이 타임스 베스트셀러신경외과 전문의이자 신경과학자가 들려주는 매력적인 뇌 이야기...,자연과학,윌북(willbook),라훌 잔디얼,372.0,"15,800원",95077356.0,0,N
...,...,...,...,...,...,...,...,...,...,...,...
17784,76788,회복탄력성,“우리가 살면서 겪는 일들은 더 나은 곳으로 향하는 계단이다.”시련과 역경에 굴하지...,자기계발,다른상상,김시현,840.0,"16,800원",128920663.0,0,N
17785,76789,"한 달이라도 좋아, 보홀이라면!","“보홀 한 달 살기, 이제 시작합니다!”엄마와 아들이 손잡고 떠난한 달짜리 여행,눈...",에세이,미다스북스(리틀미다스),박효천,2787.0,"19,000원",128920777.0,0,N
17786,76790,호감의 시작,"*** 커뮤니케이션 분야 1위, 6천만 매력 어드바이저 희렌최 화제작 ****** ...",자기계발,북로망스,희렌최,4242.0,"18,500원",128928568.0,0,N
17787,76791,봄이 오고 그대가 가다,산천초목도 그대 갈 길이 바쁜 걸 알아 일찍이 봄의 것을 내주었던가 보다. 벌써 뒷...,에세이,미루나무,이명길,90.0,"15,000원",128928919.0,0,N
17788,76792,"스물일곱, 과일로 쏘아 올린 200억",도박 빚을 갚기 급급했던 고졸 청년이연매출 200억의 사업가가 되기까지27살 청년 ...,자기계발,차선책,이진우,402.0,"18,400원",128930900.0,0,N

In [2]:
df_non_ = pd.concat([non, non2, non3, non4, non5])
df_non_

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best
0,0,총 균 쇠,문명의 생성과 번영의 수수께끼를 밝힌 세계적 명저마침내 만나는 출간 25년 기념 뉴...,인문,김영사,재레드 다이아몬드,170568.0,"29,800원",118755085.0,0,N
1,1,숙론,“누가 옳은가가 아니라 무엇이 옳은가를 찾으려는 것이다”통섭의 과학자 최재천 교수가...,인문,김영사,최재천,44487.0,"18,000원",126395984.0,0,N
2,2,친애하는 슐츠 씨,“얼마나 많은 차별이 무지에서 비롯되는가?[피너츠]의 첫 흑인 캐릭터부터 여자 옷의...,인문,어크로스,박상현,16779.0,"19,800원",126791092.0,0,N
3,3,가난한 아이들은 어떻게 어른이 되는가,“처음 만날 때는 열예닐곱 살의 청소년이었던 이들이지금은 서른 즈음의 청년이 되었다...,사회 정치,돌베개,강지나,37275.0,"17,500원",123317793.0,8,Y
4,4,팩트풀니스,빌 게이츠가 미국 모든 대학 졸업생에게 직접 선물한 화제의 책강력한 사실을 바탕으로...,인문,김영사,한스 로슬링,43548.0,"19,800원",69724044.0,0,N
...,...,...,...,...,...,...,...,...,...,...,...
17784,76788,회복탄력성,“우리가 살면서 겪는 일들은 더 나은 곳으로 향하는 계단이다.”시련과 역경에 굴하지...,자기계발,다른상상,김시현,840.0,"16,800원",128920663.0,0,N
17785,76789,"한 달이라도 좋아, 보홀이라면!","“보홀 한 달 살기, 이제 시작합니다!”엄마와 아들이 손잡고 떠난한 달짜리 여행,눈...",에세이,미다스북스(리틀미다스),박효천,2787.0,"19,000원",128920777.0,0,N
17786,76790,호감의 시작,"*** 커뮤니케이션 분야 1위, 6천만 매력 어드바이저 희렌최 화제작 ****** ...",자기계발,북로망스,희렌최,4242.0,"18,500원",128928568.0,0,N
17787,76791,봄이 오고 그대가 가다,산천초목도 그대 갈 길이 바쁜 걸 알아 일찍이 봄의 것을 내주었던가 보다. 벌써 뒷...,에세이,미루나무,이명길,90.0,"15,000원",128928919.0,0,N
17788,76792,"스물일곱, 과일로 쏘아 올린 200억",도박 빚을 갚기 급급했던 고졸 청년이연매출 200억의 사업가가 되기까지27살 청년 ...,자기계발,차선책,이진우,402.0,"18,400원",128930900.0,0,N

In [3]:
df_non_.isnull().sum()

index         0
도서 이름         0
줄거리           0
장르            0
출판사          70
작가          111
판매지수     213934
판매가           0
ID            0
month         0
best          0
dtype: int64

In [4]:
df_non_2 = df_non_

In [5]:
# '도서 이름' 열에 결측치가 있는 행을 삭제
df_non_ = df_non_.dropna(subset=['작가'])

# 결과 확인
df_non_

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best
0,0,총 균 쇠,문명의 생성과 번영의 수수께끼를 밝힌 세계적 명저마침내 만나는 출간 25년 기념 뉴...,인문,김영사,재레드 다이아몬드,170568.0,"29,800원",118755085.0,0,N
1,1,숙론,“누가 옳은가가 아니라 무엇이 옳은가를 찾으려는 것이다”통섭의 과학자 최재천 교수가...,인문,김영사,최재천,44487.0,"18,000원",126395984.0,0,N
2,2,친애하는 슐츠 씨,“얼마나 많은 차별이 무지에서 비롯되는가?[피너츠]의 첫 흑인 캐릭터부터 여자 옷의...,인문,어크로스,박상현,16779.0,"19,800원",126791092.0,0,N
3,3,가난한 아이들은 어떻게 어른이 되는가,“처음 만날 때는 열예닐곱 살의 청소년이었던 이들이지금은 서른 즈음의 청년이 되었다...,사회 정치,돌베개,강지나,37275.0,"17,500원",123317793.0,8,Y
4,4,팩트풀니스,빌 게이츠가 미국 모든 대학 졸업생에게 직접 선물한 화제의 책강력한 사실을 바탕으로...,인문,김영사,한스 로슬링,43548.0,"19,800원",69724044.0,0,N
...,...,...,...,...,...,...,...,...,...,...,...
17784,76788,회복탄력성,“우리가 살면서 겪는 일들은 더 나은 곳으로 향하는 계단이다.”시련과 역경에 굴하지...,자기계발,다른상상,김시현,840.0,"16,800원",128920663.0,0,N
17785,76789,"한 달이라도 좋아, 보홀이라면!","“보홀 한 달 살기, 이제 시작합니다!”엄마와 아들이 손잡고 떠난한 달짜리 여행,눈...",에세이,미다스북스(리틀미다스),박효천,2787.0,"19,000원",128920777.0,0,N
17786,76790,호감의 시작,"*** 커뮤니케이션 분야 1위, 6천만 매력 어드바이저 희렌최 화제작 ****** ...",자기계발,북로망스,희렌최,4242.0,"18,500원",128928568.0,0,N
17787,76791,봄이 오고 그대가 가다,산천초목도 그대 갈 길이 바쁜 걸 알아 일찍이 봄의 것을 내주었던가 보다. 벌써 뒷...,에세이,미루나무,이명길,90.0,"15,000원",128928919.0,0,N
17788,76792,"스물일곱, 과일로 쏘아 올린 200억",도박 빚을 갚기 급급했던 고졸 청년이연매출 200억의 사업가가 되기까지27살 청년 ...,자기계발,차선책,이진우,402.0,"18,400원",128930900.0,0,N

In [6]:
import pandas as pd
date = pd.read_csv('date_final_df.csv')
date

                  출간일         ID
0       2023년 05월 10일  118755085
1       2024년 05월 10일  126395984
2       2024년 06월 03일  126791092
3       2023년 11월 06일  123317793
4       2019년 03월 08일   69724044
...               ...        ...
297673  2027년 07월 24일  128920663
297674  2024년 07월 24일  128920777
297675  2024년 07월 23일  128928568
297676  2024년 07월 10일  128928919
297677  2024년 07월 15일  128930900

[297678 rows x 2 columns]

In [7]:
# '출간일'을 날짜 형식으로 변환
date['출간일'] = pd.to_datetime(date['출간일'], format='%Y년 %m월 %d일')

In [8]:
date['year'] = date['출간일'].dt.year
date['month'] = date['출간일'].dt.month
date

              출간일         ID    year  month
0      2023-05-10  118755085  2023.0    5.0
1      2024-05-10  126395984  2024.0    5.0
2      2024-06-03  126791092  2024.0    6.0
3      2023-11-06  123317793  2023.0   11.0
4      2019-03-08   69724044  2019.0    3.0
...           ...        ...     ...    ...
297673 2027-07-24  128920663  2027.0    7.0
297674 2024-07-24  128920777  2024.0    7.0
297675 2024-07-23  128928568  2024.0    7.0
297676 2024-07-10  128928919  2024.0    7.0
297677 2024-07-15  128930900  2024.0    7.0

[297678 rows x 4 columns]

In [9]:
date['year'].unique()

array([2023., 2024., 2019., 2016., 2012., 2021., 2022., 2017., 2018.,
       2004., 2014., 2020., 2010., 2015., 2008., 2013., 2009., 2007.,
       2011., 2002., 2006., 2003., 2001., 2005., 2000., 1999., 1997.,
         nan, 1989., 1996., 1994., 1998., 1995., 1978., 1993., 1985.,
       1991., 1987., 1992., 1981., 1988., 1990., 1986., 1980., 1982.,
       1975., 1983., 1979., 1984., 1976., 1961., 1977., 1970., 1974.,
       1973., 1969., 2027.])

In [10]:
df_non_['year'] = date['year']
df_non_

/tmp/ipykernel_58703/3703781358.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_non_['year'] = date['year']

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
0,0,총 균 쇠,문명의 생성과 번영의 수수께끼를 밝힌 세계적 명저마침내 만나는 출간 25년 기념 뉴...,인문,김영사,재레드 다이아몬드,170568.0,"29,800원",118755085.0,0,N,2023.0
1,1,숙론,“누가 옳은가가 아니라 무엇이 옳은가를 찾으려는 것이다”통섭의 과학자 최재천 교수가...,인문,김영사,최재천,44487.0,"18,000원",126395984.0,0,N,2024.0
2,2,친애하는 슐츠 씨,“얼마나 많은 차별이 무지에서 비롯되는가?[피너츠]의 첫 흑인 캐릭터부터 여자 옷의...,인문,어크로스,박상현,16779.0,"19,800원",126791092.0,0,N,2024.0
3,3,가난한 아이들은 어떻게 어른이 되는가,“처음 만날 때는 열예닐곱 살의 청소년이었던 이들이지금은 서른 즈음의 청년이 되었다...,사회 정치,돌베개,강지나,37275.0,"17,500원",123317793.0,8,Y,2023.0
4,4,팩트풀니스,빌 게이츠가 미국 모든 대학 졸업생에게 직접 선물한 화제의 책강력한 사실을 바탕으로...,인문,김영사,한스 로슬링,43548.0,"19,800원",69724044.0,0,N,2019.0
...,...,...,...,...,...,...,...,...,...,...,...,...
17784,76788,회복탄력성,“우리가 살면서 겪는 일들은 더 나은 곳으로 향하는 계단이다.”시련과 역경에 굴하지...,자기계발,다른상상,김시현,840.0,"16,800원",128920663.0,0,N,2001.0
17785,76789,"한 달이라도 좋아, 보홀이라면!","“보홀 한 달 살기, 이제 시작합니다!”엄마와 아들이 손잡고 떠난한 달짜리 여행,눈...",에세이,미다스북스(리틀미다스),박효천,2787.0,"19,000원",128920777.0,0,N,1995.0
17786,76790,호감의 시작,"*** 커뮤니케이션 분야 1위, 6천만 매력 어드바이저 희렌최 화제작 ****** ...",자기계발,북로망스,희렌최,4242.0,"18,500원",128928568.0,0,N,2001.0
17787,76791,봄이 오고 그대가 가다,산천초목도 그대 갈 길이 바쁜 걸 알아 일찍이 봄의 것을 내주었던가 보다. 벌써 뒷...,에세이,미루나무,이명길,90.0,"15,000원",128928919.0,0,N,2001.0
17788,76792,"스물일곱, 과일로 쏘아 올린 200억",도박 빚을 갚기 급급했던 고졸 청년이연매출 200억의 사업가가 되기까지27살 청년 ...,자기계발,차선책,이진우,402.0,"18,400원",128930900.0,0,N,2001.0

In [11]:
df_non_.isnull().sum()

index         0
도서 이름         0
줄거리           0
장르            0
출판사          70
작가            0
판매지수     213838
판매가           0
ID            0
month         0
best          0
year        126
dtype: int64

In [12]:
df_non_sorted = df_non_.sort_values(by='year', ascending=False)
df_non_sorted

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
65517,18258,세상에서 제일 이상한 그 아이,독특한 스토리 전개로 일본에서 발간 당시 라이트노벨 독자들 사이에서 화제가 됐던 작...,만화/라이트노벨,대원씨아이(단행)(대원키즈),모리야마 유우키,NaN,"6,000원",2953072.0,0,N,2024.0
20093,36449,클리어 The CLEAR 1,마법대륙 사이드리아에 마법사의 천적이 등장했다!대항마법사 사드!!!사드의 대항마법 ...,소설/시/희곡,동아,서영민,NaN,"8,000원",3221359.0,0,N,2024.0
45319,55558,노동조합 100문 100답,『노동조합 100문 100답』개정2판은 2020년 12월 개정된 노조법을 반영202...,사회 정치,매일노동뉴스,박성우,732.0,"20,000원",96432068.0,0,N,2024.0
20123,36480,미인계,중국 춘추시대 월나라의 서시를 비롯하여 당나라 양귀비까지 중국역사상 가장 아름답다고...,소설/시/희곡,오디북스,왕공상,NaN,"12,000원",3219656.0,0,N,2024.0
45320,55559,생활 속 법률 상식사전,"근처 변호사 사무실이 어디에 있었나하는 생각이 간절해지는 순간,하얘지는 머리, 새까...",사회 정치,길벗,김계형,486.0,"14,000원",77709451.0,0,N,2024.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2671,58626,기시미 이치로의 삶과 죽음,"인생은 진화가 아니라 변화다! 젊음과 늙음, 건강과 질병에 우열은 없다!기시미 이치...",인문,에쎄이,기시미 이치로,156.0,"15,000원",101903844.0,0,N,NaN
6538,63147,"아무튼, 피아노","“모든 것은 건반으로부터 시작된다”『아무튼, 피아노』나는 피아노를 배움으로써돌이킬 ...",에세이,제철소,김겨울,1020.0,"12,000원",108454817.0,2,Y,NaN
6724,63375,난세를 살아가는 지략 2,"손자병법, 명심보감 등과 같은 고전의 내용을 엮어 치열한 세상을 살아가는데 필요한 ...",자기계발,조은,범대진,12.0,"20,000원",108789289.0,0,N,NaN
10520,68144,생각의 끈 (큰글자도서),[생각의 끈]은 많은 생각보다는 좋은 생각을 하며 그것을 바르게 이루며 살 것을 말...,자기계발,이담북스(이담Books),양창삼,NaN,"35,000원",117313592.0,0,N,NaN
15940,74600,성과관리 답을 찾다,일 잘하는 S등급 동료의 성과창출 핵심 비결!‘나는 왜 성과를 창출하지 못할까?’가...,자기계발,트로이목마,류랑도,792.0,"22,000원",125104561.0,0,N,NaN

In [13]:
df_non_sorted = df_non_sorted.dropna(subset=['year'])
df_non_sorted

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
65517,18258,세상에서 제일 이상한 그 아이,독특한 스토리 전개로 일본에서 발간 당시 라이트노벨 독자들 사이에서 화제가 됐던 작...,만화/라이트노벨,대원씨아이(단행)(대원키즈),모리야마 유우키,NaN,"6,000원",2953072.0,0,N,2024.0
20093,36449,클리어 The CLEAR 1,마법대륙 사이드리아에 마법사의 천적이 등장했다!대항마법사 사드!!!사드의 대항마법 ...,소설/시/희곡,동아,서영민,NaN,"8,000원",3221359.0,0,N,2024.0
45319,55558,노동조합 100문 100답,『노동조합 100문 100답』개정2판은 2020년 12월 개정된 노조법을 반영202...,사회 정치,매일노동뉴스,박성우,732.0,"20,000원",96432068.0,0,N,2024.0
20123,36480,미인계,중국 춘추시대 월나라의 서시를 비롯하여 당나라 양귀비까지 중국역사상 가장 아름답다고...,소설/시/희곡,오디북스,왕공상,NaN,"12,000원",3219656.0,0,N,2024.0
45320,55559,생활 속 법률 상식사전,"근처 변호사 사무실이 어디에 있었나하는 생각이 간절해지는 순간,하얘지는 머리, 새까...",사회 정치,길벗,김계형,486.0,"14,000원",77709451.0,0,N,2024.0
...,...,...,...,...,...,...,...,...,...,...,...,...
36984,18564,사랑받지 못한 어글리,갖은 고난과 역경을 이겨내고영국 최초의 흑인 여성판사가 된 한 소녀의 이야기영국 최...,에세이,오픈하우스,콘스턴스 브리스코,NaN,"12,800원",3662127.0,0,N,1978.0
26155,42808,파란 3,파란만장한 인생이란 이런 것이다!무공서적만 연구하던 불우한 꼽추 청년 장대길.이세계...,소설/시/희곡,동아,서영민,NaN,"8,000원",1951827.0,0,N,1975.0
26155,62387,아인슈타인의 달팽이,"시인이 사는 곳은 “비밀 집회로 가득한 도시”(「( )」), “목마른 인적으로 유리...",소설/시/희곡,문학동네,전기철,NaN,"7,000원",2138017.0,0,N,1975.0
26155,7133,유망 아르바이트 백과사전,아르바이트에 대해서 가능한 많은 정보를 제공하여 아르바이트를 찾고자 하는 대학생들의...,자기계발,눈과마음,"장미영, 장창영, 이수라 공저",NaN,"8,000원",1423584.0,0,N,1975.0
26155,29804,도시의 정치경제학,도시를 둘러싸고 있는 자본의 운동이 지닌 여러 양태에 대해 논의하고 도시생활 속에서...,사회 정치,한울,데이비드 하비 저 / 초의수 역,NaN,"12,000원",250272.0,0,N,1975.0

In [14]:
df_non_sorted['장르'].unique()

array(['만화/라이트노벨', '소설/시/희곡', '사회 정치', '에세이', '인문', '자기계발', '경제 경영',
       '청소년', 'IT 모바일', '대학교재', '잡지', '건강 취미', '예술', '여행', '국어 외국어 사전',
       '어린이', '역사', '자연과학', '종교', '가정 살림', '수험서 자격증', '유아', '인물', '일본도서',
       '오디오북', '소설', '디자인문구', '중고 국내도서', '경영/인문', 'BOOKK(부크크)', '중고등참고서',
       '초등참고서'], dtype=object)

In [15]:
# 추출할 장르 목록
genres_to_extract = ['사회 정치', '소설/시/희곡', '에세이', '자기계발']

# 장르 열이 지정된 값 중 하나인 행만 추출
df_non_sorted = df_non_sorted[df_non_sorted['장르'].isin(genres_to_extract)]

# 결과 출력
print("Filtered Book Details:")
df_non_sorted

Filtered Book Details:

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
20093,36449,클리어 The CLEAR 1,마법대륙 사이드리아에 마법사의 천적이 등장했다!대항마법사 사드!!!사드의 대항마법 ...,소설/시/희곡,동아,서영민,NaN,"8,000원",3221359.0,0,N,2024.0
45319,55558,노동조합 100문 100답,『노동조합 100문 100답』개정2판은 2020년 12월 개정된 노조법을 반영202...,사회 정치,매일노동뉴스,박성우,732.0,"20,000원",96432068.0,0,N,2024.0
20123,36480,미인계,중국 춘추시대 월나라의 서시를 비롯하여 당나라 양귀비까지 중국역사상 가장 아름답다고...,소설/시/희곡,오디북스,왕공상,NaN,"12,000원",3219656.0,0,N,2024.0
45320,55559,생활 속 법률 상식사전,"근처 변호사 사무실이 어디에 있었나하는 생각이 간절해지는 순간,하얘지는 머리, 새까...",사회 정치,길벗,김계형,486.0,"14,000원",77709451.0,0,N,2024.0
45325,55565,상속재산 분할심판청구,"이번 개정판에서는 상속재산분할, 유류분반환청구 등에 관하여 2020년 3월 이후 선...",사회 정치,지혜와지식,오경수,288.0,"18,000원",121567014.0,0,N,2024.0
...,...,...,...,...,...,...,...,...,...,...,...,...
36984,18564,사랑받지 못한 어글리,갖은 고난과 역경을 이겨내고영국 최초의 흑인 여성판사가 된 한 소녀의 이야기영국 최...,에세이,오픈하우스,콘스턴스 브리스코,NaN,"12,800원",3662127.0,0,N,1978.0
26155,42808,파란 3,파란만장한 인생이란 이런 것이다!무공서적만 연구하던 불우한 꼽추 청년 장대길.이세계...,소설/시/희곡,동아,서영민,NaN,"8,000원",1951827.0,0,N,1975.0
26155,62387,아인슈타인의 달팽이,"시인이 사는 곳은 “비밀 집회로 가득한 도시”(「( )」), “목마른 인적으로 유리...",소설/시/희곡,문학동네,전기철,NaN,"7,000원",2138017.0,0,N,1975.0
26155,7133,유망 아르바이트 백과사전,아르바이트에 대해서 가능한 많은 정보를 제공하여 아르바이트를 찾고자 하는 대학생들의...,자기계발,눈과마음,"장미영, 장창영, 이수라 공저",NaN,"8,000원",1423584.0,0,N,1975.0
26155,29804,도시의 정치경제학,도시를 둘러싸고 있는 자본의 운동이 지닌 여러 양태에 대해 논의하고 도시생활 속에서...,사회 정치,한울,데이비드 하비 저 / 초의수 역,NaN,"12,000원",250272.0,0,N,1975.0

In [16]:
df_non_sorted['장르'].unique()

array(['소설/시/희곡', '사회 정치', '에세이', '자기계발'], dtype=object)

In [17]:
year_counts = df_non_sorted.groupby('year').size()
year_counts

year
1975.0        4
1978.0       13
1979.0        4
1980.0        8
1981.0        4
1982.0        6
1983.0        4
1985.0       30
1986.0       18
1987.0       35
1988.0       12
1989.0       53
1990.0      100
1991.0      120
1992.0      146
1993.0      235
1994.0      310
1995.0      492
1996.0      457
1997.0      906
1998.0     1256
1999.0     2218
2000.0     3400
2001.0     3055
2002.0     3779
2003.0     4125
2004.0     6778
2005.0     6731
2006.0     8610
2007.0     9935
2008.0    10772
2009.0    12363
2010.0    12168
2011.0    12860
2012.0    14038
2013.0    11685
2014.0    11689
2015.0    11160
2016.0    10682
2017.0    12024
2018.0    16253
2019.0    15370
2020.0    15967
2021.0    15425
2022.0    14876
2023.0    15450
2024.0     7689
dtype: int64

except_2024

In [18]:
df_non_sorted = df_non_sorted[df_non_sorted['year'] != 2024]
df_non_sorted

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
11853,61041,나는 야한 여자가 좋다,"도덕보다는 본능을, 이성보다는 감성을쉽고 재미있게 읽히는 경쾌한 에세이, 21년만의...",에세이,북리뷰,마광수,294.0,"13,000원",3745571.0,0,N,2023.0
51555,63780,뱀파이어의 별 2,"'뱀파이어의 꽃' 그 마지막 입맞춤,영원불멸의 뱀파이어 로맨스!‘말해서는 안 돼. ...",소설/시/희곡,테라스북,신지은,138.0,"14,500원",29373471.0,0,N,2023.0
51292,33906,수거물 폐기물,■ 사랑의 기억을 모으고 나누고 버리고… 마음이 심플해지는 감정정리법!-카피라이터 ...,에세이,폭스코너,신주희,12.0,"13,800원",20181557.0,0,N,2023.0
53713,36582,군인의 품격,"군인엄마의, 희망군대 만들기 프로젝트아들에게도 엄마에게도, 637일간의 인생수업대한...",에세이,더블엔,최혜경,12,"13,000원",30146604.0,0,N,2023.0
54414,66804,무녀굴,<한국 공포 문학 단편선>에 꾸준히 단편을 발표해 오며 실력을 닦아 온 신진오 작가...,소설/시/희곡,황금가지,신진오,126.0,"13,800원",4096725.0,0,N,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
36984,18564,사랑받지 못한 어글리,갖은 고난과 역경을 이겨내고영국 최초의 흑인 여성판사가 된 한 소녀의 이야기영국 최...,에세이,오픈하우스,콘스턴스 브리스코,NaN,"12,800원",3662127.0,0,N,1978.0
26155,42808,파란 3,파란만장한 인생이란 이런 것이다!무공서적만 연구하던 불우한 꼽추 청년 장대길.이세계...,소설/시/희곡,동아,서영민,NaN,"8,000원",1951827.0,0,N,1975.0
26155,62387,아인슈타인의 달팽이,"시인이 사는 곳은 “비밀 집회로 가득한 도시”(「( )」), “목마른 인적으로 유리...",소설/시/희곡,문학동네,전기철,NaN,"7,000원",2138017.0,0,N,1975.0
26155,7133,유망 아르바이트 백과사전,아르바이트에 대해서 가능한 많은 정보를 제공하여 아르바이트를 찾고자 하는 대학생들의...,자기계발,눈과마음,"장미영, 장창영, 이수라 공저",NaN,"8,000원",1423584.0,0,N,1975.0
26155,29804,도시의 정치경제학,도시를 둘러싸고 있는 자본의 운동이 지닌 여러 양태에 대해 논의하고 도시생활 속에서...,사회 정치,한울,데이비드 하비 저 / 초의수 역,NaN,"12,000원",250272.0,0,N,1975.0

In [19]:
df_non_sorted = df_non_sorted[df_non_sorted['year'] >= 2017]
df_non_sorted

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
11853,61041,나는 야한 여자가 좋다,"도덕보다는 본능을, 이성보다는 감성을쉽고 재미있게 읽히는 경쾌한 에세이, 21년만의...",에세이,북리뷰,마광수,294.0,"13,000원",3745571.0,0,N,2023.0
51555,63780,뱀파이어의 별 2,"'뱀파이어의 꽃' 그 마지막 입맞춤,영원불멸의 뱀파이어 로맨스!‘말해서는 안 돼. ...",소설/시/희곡,테라스북,신지은,138.0,"14,500원",29373471.0,0,N,2023.0
51292,33906,수거물 폐기물,■ 사랑의 기억을 모으고 나누고 버리고… 마음이 심플해지는 감정정리법!-카피라이터 ...,에세이,폭스코너,신주희,12.0,"13,800원",20181557.0,0,N,2023.0
53713,36582,군인의 품격,"군인엄마의, 희망군대 만들기 프로젝트아들에게도 엄마에게도, 637일간의 인생수업대한...",에세이,더블엔,최혜경,12,"13,000원",30146604.0,0,N,2023.0
54414,66804,무녀굴,<한국 공포 문학 단편선>에 꾸준히 단편을 발표해 오며 실력을 닦아 온 신진오 작가...,소설/시/희곡,황금가지,신진오,126.0,"13,800원",4096725.0,0,N,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8570,65655,자기계발 코칭전문가 4,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"15,100원",112905001.0,0,N,2017.0
29816,68589,모두가 예술이다,계간 문예지 『시와세계』와 『현대불교신문』이 공동으로 제정한 <이상시문학상>은 시인...,소설/시/희곡,시와세계,이승훈,NaN,"8,000원",3081397.0,0,N,2017.0
8573,65658,자기계발 코칭전문가 1,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"14,700원",112905012.0,0,N,2017.0
8569,65654,자기계발 코칭전문가 5,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"25,300원",112904997.0,0,N,2017.0
6391,31192,이상 시 전집,한국문학사에서 유례를 찾기 힘들 만큼 실험적이고 전위적인 문학적 조형 언어로 ‘시각...,소설/시/희곡,민음사,이상,5880.0,"16,000원",112219465.0,0,N,2017.0

In [20]:
df_non_sorted[df_non_sorted['best'] == 'Y']

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
51188,33777,합리적 남자,남자와 여자가 짝짓기 대상을 선택하는 방식이 다른 것은 인간의 DNA에 깊이 새겨져...,자기계발,아니마,롤로 토마시,2754,"13,000원",20053430.0,5,Y,2023.0
9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,"17,000원",66318782.0,1,Y,2023.0
11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,"13,800원",46906835.0,14,Y,2023.0
54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546129.0,2,Y,2023.0
54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546136.0,2,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6385,31185,없음의 대명사,“없음은 있었음을 끊임없이 두드릴 것이다”‘웃음’과 ‘울음’이 나란히 놓이고‘무표정...,소설/시/희곡,문학과지성사,오은,9021.0,"12,000원",118785759.0,2,Y,2017.0
6305,6903,풀,일본군 ‘위안부’ 피해 할머니의 삶을 그린 장편 만화평화 발자국 열아홉 번째 책은 ...,사회 정치,보리,김금숙,NaN,"26,000원",44332143.0,1,Y,2017.0
6378,31177,풀꽃,‘자세히 보아야/ 예쁘다// 오래 보아야/ 사랑스럽다// 너도 그렇다.’ 스물넉 자...,소설/시/희곡,지혜,나태주,9744.0,"11,000원",99351974.0,2,Y,2017.0
6392,31193,꽃샘바람에 흔들린다면 너는 꽃,섬세한 언어 감각과 서정성 -삶 속에서 심호흡이 필요할 때가슴으로 암송하는 시들시집...,소설/시/희곡,수오서재,류시화,6303.0,"13,500원",108590831.0,5,Y,2017.0
6436,31239,수학자의 아침,"‘그렇지 않았던 것들’을 포착해내는 아침의 감각1993년 등단한 후 지금까지, 세 ...",소설/시/희곡,문학과지성사,김소연,4026.0,"12,000원",11406090.0,2,Y,2017.0

베스트 셀러 생애주기

In [21]:
df_book_details = pd.read_csv('book_details.csv')

In [22]:
df_book_details

,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID
0,나의 영어 사춘기,"대한민국 대표 영어강사 이시원, 영포자들의 닫힌 말문을 열게하다!8주면 누구나 영어...",국어 외국어 사전,시원스쿨닷컴,이시원,72.0,"13,500원",57717060
1,신경 끄기의 기술,아마존·뉴욕타임스 베스트셀러 1위150만 부 돌파! 아마존 53주 연속 베스트셀러2...,자기계발,갤리온,마크 맨슨,19326.0,"17,800원",54233937
2,82년생 김지영,"공포, 피로, 당황, 놀람, 혼란, 좌절의 연속에 대한 한국 여자의 인생 현장 보고...",소설/시/희곡,민음사,조남주,3306.0,"14,000원",32972572
3,언어의 온도,“말과 글에는 나름의 온도가 있다”말과 글에는 나름의 온도가 있다. 따뜻함과 차가움...,에세이,말글터,이기주,30606.0,"13,800원",30387696
4,랩걸 Lab Girl,"2016년 출간과 함께 베스트셀러에 오르며 뜨거운 관심을 받은 <랩걸-나무, 과학 ...",자연과학,알마,호프 자런,10398.0,"20,000원",36390807
...,...,...,...,...,...,...,...,...
77400,2024 해커스군무원 혜원국어 실전동형모의고사 20회분,최신 기출 경향 완벽 반영!20회분의 동형모의고사로 극대화하는 실전 감각!변화하는 ...,수험서 자격증,해커스군무원,고혜원,7962.0,"23,000원",126394099
77401,2024 유휘운 행정법총론 실전동형 모의고사,『2024 유휘운 행정법총론 실전동형 모의고사』는 2024년 공무원 행정법 시험 대...,수험서 자격증,메가스터디교육(공무원),유휘운,24039.0,"9,000원",124838794
77402,ETS 토익 정기시험 실전 1000 Vol. 1 RC(리딩),"토익 실전문제, 이보다 더 완벽할 순 없다!최신 토익시험 경향이 한눈에 보이는 ET...",국어 외국어 사전,YBM(와이비엠),ETS,37827.0,"19,800원",119661061
77403,나혼자 끝내는 독학 일본어 첫걸음,"일본어 20일 기초 완성, 혼자서도 문제 없다!가나&한자 쓰기, 단어 암기, 복습,...",국어 외국어 사전,넥서스JAPANESE,넥서스콘텐츠개발팀,19767.0,"15,000원",116046987
77404,해리포터와 비밀의 방 1,"해리 포터 세대의, 해리 포터 세대를 위한, 해리 포터 세대에 의한 새 번역!‘21...",소설/시/희곡,문학수첩,J.K. 롤링,25395.0,"9,000원",82938415

In [23]:
best_date = pd.read_csv('goods_numbers_with_dates.csv')
best_date

       year  month  data_goods_no
0      2018      1       57717060
1      2018      1       54233937
2      2018      1       32972572
3      2018      1       30387696
4      2018      1       36390807
...     ...    ...            ...
77400  2024      6      126394099
77401  2024      6      124838794
77402  2024      6      119661061
77403  2024      6      116046987
77404  2024      6       82938415

[77405 rows x 3 columns]

In [24]:
best_date.isnull().sum()

year             0
month            0
data_goods_no    0
dtype: int64

In [25]:
date

              출간일         ID    year  month
0      2023-05-10  118755085  2023.0    5.0
1      2024-05-10  126395984  2024.0    5.0
2      2024-06-03  126791092  2024.0    6.0
3      2023-11-06  123317793  2023.0   11.0
4      2019-03-08   69724044  2019.0    3.0
...           ...        ...     ...    ...
297673 2027-07-24  128920663  2027.0    7.0
297674 2024-07-24  128920777  2024.0    7.0
297675 2024-07-23  128928568  2024.0    7.0
297676 2024-07-10  128928919  2024.0    7.0
297677 2024-07-15  128930900  2024.0    7.0

[297678 rows x 4 columns]

In [26]:
date.isnull().sum()

출간일      304
ID         0
year     304
month    304
dtype: int64

In [27]:
# 출간일 2017~2024 자르기
date = date[date['year'] != 2024] 
date = date[date['year'] >= 2017]
date

              출간일         ID    year  month
0      2023-05-10  118755085  2023.0    5.0
3      2023-11-06  123317793  2023.0   11.0
4      2019-03-08   69724044  2019.0    3.0
6      2023-08-30  122091079  2023.0    8.0
9      2023-11-10  123743926  2023.0   11.0
...           ...        ...     ...    ...
297089 2023-09-18  126822330  2023.0    9.0
297250 2023-12-10  127066962  2023.0   12.0
297634 2023-06-12  128818595  2023.0    6.0
297635 2023-06-12  128818647  2023.0    6.0
297673 2027-07-24  128920663  2027.0    7.0

[100084 rows x 4 columns]

In [28]:
date.isnull().sum()

출간일      0
ID       0
year     0
month    0
dtype: int64

In [29]:
# 출간일 2017~2024 자르기
# best_date에서 date의 ID와 data_goods_no가 일치하는 행 필터링 
best_date_filter_2017 = best_date[best_date["data_goods_no"].isin(date["ID"])]

best_date_filter_2017

       year  month  data_goods_no
1      2018      1       54233937
6      2018      1       46659527
7      2018      1       57817824
8      2018      1       57430679
9      2018      1       57430704
...     ...    ...            ...
77365  2024      6       22793441
77379  2024      6       46659527
77390  2024      6      121925411
77391  2024      6      120178685
77404  2024      6       82938415

[16717 rows x 3 columns]

In [30]:
date_filter_2017_b = date[date["ID"].isin(best_date_filter_2017["data_goods_no"])]
date_filter_2017_b

              출간일         ID    year  month
0      2023-05-10  118755085  2023.0    5.0
3      2023-11-06  123317793  2023.0   11.0
4      2019-03-08   69724044  2019.0    3.0
6      2023-08-30  122091079  2023.0    8.0
9      2023-11-10  123743926  2023.0   11.0
...           ...        ...     ...    ...
294887 2023-12-25  124184330  2023.0   12.0
294903 2023-12-22  124201150  2023.0   12.0
294909 2023-12-20  124201716  2023.0   12.0
294948 2023-12-27  124226256  2023.0   12.0
294953 2023-12-21  124227999  2023.0   12.0

[4501 rows x 4 columns]

In [31]:
for idx, row in best_date_filter_2017.iterrows():
    for mer_idx, mer_row in date_filter_2017_b.iterrows():
        if mer_row['ID'] == row['data_goods_no']:
            best_date_filter_2017.at[idx, '출간일'] = mer_row['출간일']

/tmp/ipykernel_58703/2466063951.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  best_date_filter_2017.at[idx, '출간일'] = mer_row['출간일']

In [32]:
best_date_filter_2017

       year  month  data_goods_no        출간일
1      2018      1       54233937 2017-10-27
6      2018      1       46659527 2017-09-22
7      2018      1       57817824 2018-01-08
8      2018      1       57430679 2017-12-12
9      2018      1       57430704 2017-12-12
...     ...    ...            ...        ...
77365  2024      6       22793441 2022-11-14
77379  2024      6       46659527 2017-09-22
77390  2024      6      121925411 2023-08-23
77391  2024      6      120178685 2023-07-27
77404  2024      6       82938415 2019-11-19

[16717 rows x 4 columns]

In [33]:
best_date_filter_2017['year_출간일'] = best_date_filter_2017['출간일'].dt.year

/tmp/ipykernel_58703/246063368.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  best_date_filter_2017['year_출간일'] = best_date_filter_2017['출간일'].dt.year

In [34]:
best_date_filter_2017_restore = best_date_filter_2017

In [35]:
best_date_filter_2017 = best_date_filter_2017[best_date_filter_2017['year'] >= best_date_filter_2017['year_출간일']]

In [36]:
best_date_filter_2017

       year  month  data_goods_no        출간일  year_출간일
1      2018      1       54233937 2017-10-27      2017
6      2018      1       46659527 2017-09-22      2017
7      2018      1       57817824 2018-01-08      2018
8      2018      1       57430679 2017-12-12      2017
9      2018      1       57430704 2017-12-12      2017
...     ...    ...            ...        ...       ...
77365  2024      6       22793441 2022-11-14      2022
77379  2024      6       46659527 2017-09-22      2017
77390  2024      6      121925411 2023-08-23      2023
77391  2024      6      120178685 2023-07-27      2023
77404  2024      6       82938415 2019-11-19      2019

[16336 rows x 5 columns]

In [37]:
df_non_sorted_filtered = df_non_sorted

In [38]:
df_non_sorted_filtered

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
11853,61041,나는 야한 여자가 좋다,"도덕보다는 본능을, 이성보다는 감성을쉽고 재미있게 읽히는 경쾌한 에세이, 21년만의...",에세이,북리뷰,마광수,294.0,"13,000원",3745571.0,0,N,2023.0
51555,63780,뱀파이어의 별 2,"'뱀파이어의 꽃' 그 마지막 입맞춤,영원불멸의 뱀파이어 로맨스!‘말해서는 안 돼. ...",소설/시/희곡,테라스북,신지은,138.0,"14,500원",29373471.0,0,N,2023.0
51292,33906,수거물 폐기물,■ 사랑의 기억을 모으고 나누고 버리고… 마음이 심플해지는 감정정리법!-카피라이터 ...,에세이,폭스코너,신주희,12.0,"13,800원",20181557.0,0,N,2023.0
53713,36582,군인의 품격,"군인엄마의, 희망군대 만들기 프로젝트아들에게도 엄마에게도, 637일간의 인생수업대한...",에세이,더블엔,최혜경,12,"13,000원",30146604.0,0,N,2023.0
54414,66804,무녀굴,<한국 공포 문학 단편선>에 꾸준히 단편을 발표해 오며 실력을 닦아 온 신진오 작가...,소설/시/희곡,황금가지,신진오,126.0,"13,800원",4096725.0,0,N,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8570,65655,자기계발 코칭전문가 4,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"15,100원",112905001.0,0,N,2017.0
29816,68589,모두가 예술이다,계간 문예지 『시와세계』와 『현대불교신문』이 공동으로 제정한 <이상시문학상>은 시인...,소설/시/희곡,시와세계,이승훈,NaN,"8,000원",3081397.0,0,N,2017.0
8573,65658,자기계발 코칭전문가 1,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"14,700원",112905012.0,0,N,2017.0
8569,65654,자기계발 코칭전문가 5,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"25,300원",112904997.0,0,N,2017.0
6391,31192,이상 시 전집,한국문학사에서 유례를 찾기 힘들 만큼 실험적이고 전위적인 문학적 조형 언어로 ‘시각...,소설/시/희곡,민음사,이상,5880.0,"16,000원",112219465.0,0,N,2017.0

In [39]:
df_non_sorted_filtered_best = df_non_sorted_filtered[df_non_sorted_filtered['best'] == 'Y']
df_non_sorted_filtered_best

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
51188,33777,합리적 남자,남자와 여자가 짝짓기 대상을 선택하는 방식이 다른 것은 인간의 DNA에 깊이 새겨져...,자기계발,아니마,롤로 토마시,2754,"13,000원",20053430.0,5,Y,2023.0
9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,"17,000원",66318782.0,1,Y,2023.0
11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,"13,800원",46906835.0,14,Y,2023.0
54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546129.0,2,Y,2023.0
54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546136.0,2,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6385,31185,없음의 대명사,“없음은 있었음을 끊임없이 두드릴 것이다”‘웃음’과 ‘울음’이 나란히 놓이고‘무표정...,소설/시/희곡,문학과지성사,오은,9021.0,"12,000원",118785759.0,2,Y,2017.0
6305,6903,풀,일본군 ‘위안부’ 피해 할머니의 삶을 그린 장편 만화평화 발자국 열아홉 번째 책은 ...,사회 정치,보리,김금숙,NaN,"26,000원",44332143.0,1,Y,2017.0
6378,31177,풀꽃,‘자세히 보아야/ 예쁘다// 오래 보아야/ 사랑스럽다// 너도 그렇다.’ 스물넉 자...,소설/시/희곡,지혜,나태주,9744.0,"11,000원",99351974.0,2,Y,2017.0
6392,31193,꽃샘바람에 흔들린다면 너는 꽃,섬세한 언어 감각과 서정성 -삶 속에서 심호흡이 필요할 때가슴으로 암송하는 시들시집...,소설/시/희곡,수오서재,류시화,6303.0,"13,500원",108590831.0,5,Y,2017.0
6436,31239,수학자의 아침,"‘그렇지 않았던 것들’을 포착해내는 아침의 감각1993년 등단한 후 지금까지, 세 ...",소설/시/희곡,문학과지성사,김소연,4026.0,"12,000원",11406090.0,2,Y,2017.0

In [40]:
df_non_sorted_filtered_best = df_non_sorted_filtered_best[df_non_sorted_filtered_best["ID"].isin(best_date_filter_2017["data_goods_no"])]
df_non_sorted_filtered_best

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,"17,000원",66318782.0,1,Y,2023.0
11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,"13,800원",46906835.0,14,Y,2023.0
54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546129.0,2,Y,2023.0
54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546136.0,2,Y,2023.0
9819,58821,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,2346.0,"15,800원",59674622.0,6,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6414,31215,너의 아름다움이 온통 글이 될까봐,"여전히 깊고,보다 새로우며,전에 없이 다양할 것입니다.한국시에 다가올 파란과 만장을...",소설/시/희곡,문학동네,황유원,7248.0,"12,000원",56940287.0,11,Y,2017.0
6385,31185,없음의 대명사,“없음은 있었음을 끊임없이 두드릴 것이다”‘웃음’과 ‘울음’이 나란히 놓이고‘무표정...,소설/시/희곡,문학과지성사,오은,9021.0,"12,000원",118785759.0,2,Y,2017.0
6305,6903,풀,일본군 ‘위안부’ 피해 할머니의 삶을 그린 장편 만화평화 발자국 열아홉 번째 책은 ...,사회 정치,보리,김금숙,NaN,"26,000원",44332143.0,1,Y,2017.0
6378,31177,풀꽃,‘자세히 보아야/ 예쁘다// 오래 보아야/ 사랑스럽다// 너도 그렇다.’ 스물넉 자...,소설/시/희곡,지혜,나태주,9744.0,"11,000원",99351974.0,2,Y,2017.0
6392,31193,꽃샘바람에 흔들린다면 너는 꽃,섬세한 언어 감각과 서정성 -삶 속에서 심호흡이 필요할 때가슴으로 암송하는 시들시집...,소설/시/희곡,수오서재,류시화,6303.0,"13,500원",108590831.0,5,Y,2017.0

In [41]:
df_non_sorted_filtered_nonbest =  df_non_sorted_filtered[df_non_sorted_filtered['best'] == 'N']
df_non_sorted_filtered_nonbest

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
11853,61041,나는 야한 여자가 좋다,"도덕보다는 본능을, 이성보다는 감성을쉽고 재미있게 읽히는 경쾌한 에세이, 21년만의...",에세이,북리뷰,마광수,294.0,"13,000원",3745571.0,0,N,2023.0
51555,63780,뱀파이어의 별 2,"'뱀파이어의 꽃' 그 마지막 입맞춤,영원불멸의 뱀파이어 로맨스!‘말해서는 안 돼. ...",소설/시/희곡,테라스북,신지은,138.0,"14,500원",29373471.0,0,N,2023.0
51292,33906,수거물 폐기물,■ 사랑의 기억을 모으고 나누고 버리고… 마음이 심플해지는 감정정리법!-카피라이터 ...,에세이,폭스코너,신주희,12.0,"13,800원",20181557.0,0,N,2023.0
53713,36582,군인의 품격,"군인엄마의, 희망군대 만들기 프로젝트아들에게도 엄마에게도, 637일간의 인생수업대한...",에세이,더블엔,최혜경,12,"13,000원",30146604.0,0,N,2023.0
54414,66804,무녀굴,<한국 공포 문학 단편선>에 꾸준히 단편을 발표해 오며 실력을 닦아 온 신진오 작가...,소설/시/희곡,황금가지,신진오,126.0,"13,800원",4096725.0,0,N,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8570,65655,자기계발 코칭전문가 4,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"15,100원",112905001.0,0,N,2017.0
29816,68589,모두가 예술이다,계간 문예지 『시와세계』와 『현대불교신문』이 공동으로 제정한 <이상시문학상>은 시인...,소설/시/희곡,시와세계,이승훈,NaN,"8,000원",3081397.0,0,N,2017.0
8573,65658,자기계발 코칭전문가 1,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"14,700원",112905012.0,0,N,2017.0
8569,65654,자기계발 코칭전문가 5,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"25,300원",112904997.0,0,N,2017.0
6391,31192,이상 시 전집,한국문학사에서 유례를 찾기 힘들 만큼 실험적이고 전위적인 문학적 조형 언어로 ‘시각...,소설/시/희곡,민음사,이상,5880.0,"16,000원",112219465.0,0,N,2017.0

In [42]:
df_non_sorted_filtered_finalmerged = pd.concat([df_non_sorted_filtered_nonbest, df_non_sorted_filtered_best])
df_non_sorted_filtered_finalmerged

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
11853,61041,나는 야한 여자가 좋다,"도덕보다는 본능을, 이성보다는 감성을쉽고 재미있게 읽히는 경쾌한 에세이, 21년만의...",에세이,북리뷰,마광수,294.0,"13,000원",3745571.0,0,N,2023.0
51555,63780,뱀파이어의 별 2,"'뱀파이어의 꽃' 그 마지막 입맞춤,영원불멸의 뱀파이어 로맨스!‘말해서는 안 돼. ...",소설/시/희곡,테라스북,신지은,138.0,"14,500원",29373471.0,0,N,2023.0
51292,33906,수거물 폐기물,■ 사랑의 기억을 모으고 나누고 버리고… 마음이 심플해지는 감정정리법!-카피라이터 ...,에세이,폭스코너,신주희,12.0,"13,800원",20181557.0,0,N,2023.0
53713,36582,군인의 품격,"군인엄마의, 희망군대 만들기 프로젝트아들에게도 엄마에게도, 637일간의 인생수업대한...",에세이,더블엔,최혜경,12,"13,000원",30146604.0,0,N,2023.0
54414,66804,무녀굴,<한국 공포 문학 단편선>에 꾸준히 단편을 발표해 오며 실력을 닦아 온 신진오 작가...,소설/시/희곡,황금가지,신진오,126.0,"13,800원",4096725.0,0,N,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6414,31215,너의 아름다움이 온통 글이 될까봐,"여전히 깊고,보다 새로우며,전에 없이 다양할 것입니다.한국시에 다가올 파란과 만장을...",소설/시/희곡,문학동네,황유원,7248.0,"12,000원",56940287.0,11,Y,2017.0
6385,31185,없음의 대명사,“없음은 있었음을 끊임없이 두드릴 것이다”‘웃음’과 ‘울음’이 나란히 놓이고‘무표정...,소설/시/희곡,문학과지성사,오은,9021.0,"12,000원",118785759.0,2,Y,2017.0
6305,6903,풀,일본군 ‘위안부’ 피해 할머니의 삶을 그린 장편 만화평화 발자국 열아홉 번째 책은 ...,사회 정치,보리,김금숙,NaN,"26,000원",44332143.0,1,Y,2017.0
6378,31177,풀꽃,‘자세히 보아야/ 예쁘다// 오래 보아야/ 사랑스럽다// 너도 그렇다.’ 스물넉 자...,소설/시/희곡,지혜,나태주,9744.0,"11,000원",99351974.0,2,Y,2017.0
6392,31193,꽃샘바람에 흔들린다면 너는 꽃,섬세한 언어 감각과 서정성 -삶 속에서 심호흡이 필요할 때가슴으로 암송하는 시들시집...,소설/시/희곡,수오서재,류시화,6303.0,"13,500원",108590831.0,5,Y,2017.0

In [43]:
df_non_sorted_filtered_finalmerged['장르'].unique()

array(['에세이', '소설/시/희곡', '자기계발', '사회 정치'], dtype=object)

##### Down Sampling

In [44]:
# 장르별 데이터 개수
genre_counts = df_non_sorted_filtered_nonbest['장르'].value_counts()

# 장르별 비율 계산 (전체 대비 비율)
genre_percentage = genre_counts / len(df_non_sorted_filtered_nonbest) * 100

# 결과 출력
genre_percentage

장르
소설/시/희곡    60.065133
사회 정치      15.317788
에세이        14.438399
자기계발       10.178680
Name: count, dtype: float64

In [44]:
# 베스트 셀러와 비베스트 셀러 데이터 분리
bestsellers = df_non_sorted_filtered_best
non_bestsellers = df_non_sorted_filtered_nonbest

1:3

In [46]:
# 베스트 셀러 장르 비율
genre_distribution = {
    '소설/시/희곡': 60.065133,
    '에세이': 14.438399,
    '자기계발': 10.178680,
    '사회 정치': 15.317788
}

# 목표 총 개수
target_count = 4887

# 각 장르별 샘플 수 계산
samples_per_genre = {genre: int((percentage / 100) * target_count) for genre, percentage in genre_distribution.items()}

# 샘플 수가 해당 장르의 데이터 개수를 초과하지 않도록 조정
downsampled_non_bestsellers = pd.DataFrame()

for genre, num_samples in samples_per_genre.items():
    genre_data = non_bestsellers[non_bestsellers['장르'] == genre]
    if len(genre_data) < num_samples:
        num_samples = len(genre_data)  # 장르 데이터가 부족하면 전체 데이터 개수로 설정
    genre_samples = genre_data.sample(n=num_samples, replace=True)  # 필요시 중복 허용
    downsampled_non_bestsellers = pd.concat([downsampled_non_bestsellers, genre_samples])

# 최종 데이터프레임 생성
final_dataset_3 = pd.concat([bestsellers, downsampled_non_bestsellers])

# 결과 출력 및 확인
print("총 데이터 개수:", len(final_dataset_3))
final_dataset_3

총 데이터 개수: 6514

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,"17,000원",66318782.0,1,Y,2023.0
11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,"13,800원",46906835.0,14,Y,2023.0
54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546129.0,2,Y,2023.0
54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546136.0,2,Y,2023.0
9819,58821,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,2346.0,"15,800원",59674622.0,6,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
22588,25222,사회혁신과 디자인적 사고,"디자인 씽킹(Design Thinking), 디자인의 가치와 본질에 대한 인식 전환...",사회 정치,밥북,조영식,60.0,"13,000원",102007457.0,0,N,2021.0
20632,22828,기본소득 비판,‘기본소득 소개서’이자 ‘기본소득 비판서’로보편적 복지국가의 성숙한 발전을 촉구하는...,사회 정치,밈,이상이,114.0,"17,000원",101658735.0,0,N,2019.0
16281,18022,"대한민국의 신미래전략, 아세안이 답이다","신남방정책, 아세안이 답이다이 책은 대한민국의 신성장동력으로 부상하고 있는 아세안과...",사회 정치,글로벌콘텐츠,한동만,NaN,"16,500원",83532323.0,0,N,2019.0
10976,11817,김정은시대 북한사회복지,"이 책을 내용 중심으로 구분하면 북한사회복지의 기초부문, 기본 현황과 핵심 법제, ...",사회 정치,선인,이철수,NaN,"85,000원",89406903.0,0,N,2020.0
19339,21475,중국 외교 읽기,중국은 무엇을 원하는가?중국을 바라보는 세계의 시선은 온갖 편견에 휩싸여 있다. 일...,사회 정치,시그마북스,케리 브라운,12.0,"16,000원",64585274.0,0,N,2018.0

In [47]:
# 장르별 데이터 개수
genre_counts = final_dataset_3['장르'].value_counts()

# 장르별 비율 계산 (전체 대비 비율)
genre_percentage = genre_counts / len(final_dataset_3) * 100

# 결과 출력
genre_percentage

장르
소설/시/희곡    54.313786
사회 정치      16.456862
에세이        16.287995
자기계발       12.941357
Name: count, dtype: float64

3:1 (장르 비율 동일)

In [45]:
# 베스트 셀러 장르 비율
genre_distribution = {
    '소설/시/희곡': 25,
    '에세이': 25,
    '자기계발': 25,
    '사회 정치': 25
}

# 목표 총 개수
target_count = 4887

# 각 장르별 샘플 수 계산
samples_per_genre = {genre: int((percentage / 100) * target_count) for genre, percentage in genre_distribution.items()}

# 샘플 수가 해당 장르의 데이터 개수를 초과하지 않도록 조정
downsampled_non_bestsellers = pd.DataFrame()

for genre, num_samples in samples_per_genre.items():
    genre_data = non_bestsellers[non_bestsellers['장르'] == genre]
    if len(genre_data) < num_samples:
        num_samples = len(genre_data)  # 장르 데이터가 부족하면 전체 데이터 개수로 설정
    genre_samples = genre_data.sample(n=num_samples, replace=True)  # 필요시 중복 허용
    downsampled_non_bestsellers = pd.concat([downsampled_non_bestsellers, genre_samples])

# 최종 데이터프레임 생성
final_dataset_3 = pd.concat([bestsellers, downsampled_non_bestsellers])

# 결과 출력 및 확인
print("총 데이터 개수:", len(final_dataset_3))
final_dataset_3

총 데이터 개수: 6513

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,"17,000원",66318782.0,1,Y,2023.0
11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,"13,800원",46906835.0,14,Y,2023.0
54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546129.0,2,Y,2023.0
54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546136.0,2,Y,2023.0
9819,58821,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,2346.0,"15,800원",59674622.0,6,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
28672,32917,한국가정과 다문화가정 내 배우자 폭력의 유형 및 특성 비교 연구,한국가정과 다문화가정 내 배우자 폭력의 유형 및 특성 비교 연구일반적으로 배우자 폭...,사회 정치,집문당,그레이스 정,12.0,"13,000원",90334722.0,0,N,2020.0
32554,37127,특수교사119,"“교사의 노력과 고민만큼 학생이 성장한다.”수업은 기본이고 생활습관지도, 진로직업지...",사회 정치,에듀니티,원재연,1392.0,"19,800원",89958290.0,0,N,2017.0
43320,51029,스마트융합 환경에서의 박물관 미술관 기능개선의 방향 연구,이 책은 한국문화관광연구원의 스마트융합 환경에서의 박물관 미술관 기능개선의 방향 연...,사회 정치,한국문화관광연구원,류정아,NaN,"9,000원",64484555.0,0,N,2017.0
49677,61844,한국의 전투와 무기,"이 책은 우리 역사에서 중요한 전투를 골라 전투의 원인과 경과 및 결과, 전투에 참...",사회 정치,현암사,신현득,12.0,"15,000원",2943994.0,0,N,2020.0
48827,60788,전쟁과 경영,세계에서 가장 크고 강한 조직인 미국 육군의 변혁을성공으로 이끈 지도자들의 생생한 ...,사회 정치,지식노마드,고든 R. 설리번,NaN,"18,900원",76106872.0,0,N,2018.0

In [46]:
# 장르별 데이터 개수
genre_counts = final_dataset_3['장르'].value_counts()

# 장르별 비율 계산 (전체 대비 비율)
genre_percentage = genre_counts / len(final_dataset_3) * 100

# 결과 출력
genre_percentage

장르
소설/시/희곡    28.005527
에세이        24.213112
자기계발       24.059573
사회 정치      23.721787
Name: count, dtype: float64

In [47]:
final_dataset_3.to_csv('book_1_3_samegenre.csv')
book_1_3 = pd.read_csv('book_1_3_samegenre.csv')
book_1_3

,Unnamed: 0,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
0,9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,"17,000원",66318782.0,1,Y,2023.0
1,11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,"13,800원",46906835.0,14,Y,2023.0
2,54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546129.0,2,Y,2023.0
3,54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546136.0,2,Y,2023.0
4,9819,58821,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,2346.0,"15,800원",59674622.0,6,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6508,28672,32917,한국가정과 다문화가정 내 배우자 폭력의 유형 및 특성 비교 연구,한국가정과 다문화가정 내 배우자 폭력의 유형 및 특성 비교 연구일반적으로 배우자 폭...,사회 정치,집문당,그레이스 정,12.0,"13,000원",90334722.0,0,N,2020.0
6509,32554,37127,특수교사119,"“교사의 노력과 고민만큼 학생이 성장한다.”수업은 기본이고 생활습관지도, 진로직업지...",사회 정치,에듀니티,원재연,1392.0,"19,800원",89958290.0,0,N,2017.0
6510,43320,51029,스마트융합 환경에서의 박물관 미술관 기능개선의 방향 연구,이 책은 한국문화관광연구원의 스마트융합 환경에서의 박물관 미술관 기능개선의 방향 연...,사회 정치,한국문화관광연구원,류정아,NaN,"9,000원",64484555.0,0,N,2017.0
6511,49677,61844,한국의 전투와 무기,"이 책은 우리 역사에서 중요한 전투를 골라 전투의 원인과 경과 및 결과, 전투에 참...",사회 정치,현암사,신현득,12.0,"15,000원",2943994.0,0,N,2020.0
6512,48827,60788,전쟁과 경영,세계에서 가장 크고 강한 조직인 미국 육군의 변혁을성공으로 이끈 지도자들의 생생한 ...,사회 정치,지식노마드,고든 R. 설리번,NaN,"18,900원",76106872.0,0,N,2018.0

1:4

In [49]:
# 베스트 셀러 장르 비율
genre_distribution = {
    '소설/시/희곡': 60.065133,
    '에세이': 14.438399,
    '자기계발': 10.178680,
    '사회 정치': 15.317788
}

# 목표 총 개수
target_count = 6516

# 각 장르별 샘플 수 계산
samples_per_genre = {genre: int((percentage / 100) * target_count) for genre, percentage in genre_distribution.items()}

# 샘플 수가 해당 장르의 데이터 개수를 초과하지 않도록 조정
downsampled_non_bestsellers = pd.DataFrame()

for genre, num_samples in samples_per_genre.items():
    genre_data = non_bestsellers[non_bestsellers['장르'] == genre]
    if len(genre_data) < num_samples:
        num_samples = len(genre_data)  # 장르 데이터가 부족하면 전체 데이터 개수로 설정
    genre_samples = genre_data.sample(n=num_samples, replace=True)  # 필요시 중복 허용
    downsampled_non_bestsellers = pd.concat([downsampled_non_bestsellers, genre_samples])

# 최종 데이터프레임 생성
final_dataset_4 = pd.concat([bestsellers, downsampled_non_bestsellers])

# 결과 출력 및 확인
print("총 데이터 개수:", len(final_dataset_4))
final_dataset_4

총 데이터 개수: 8143

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,"17,000원",66318782.0,1,Y,2023.0
11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,"13,800원",46906835.0,14,Y,2023.0
54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546129.0,2,Y,2023.0
54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546136.0,2,Y,2023.0
9819,58821,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,2346.0,"15,800원",59674622.0,6,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
43368,51121,2017년 빈곤통계연보,빈곤 및 불평등 지표는 취약계층과 사회정책 대상자의 규모 및 관련 정책의 효과성을 ...,사회 정치,한국보건사회연구원,기초보장연구실,NaN,"8,000원",60492401.0,0,N,2017.0
37765,43111,스마트한 과학 수업! 1,스마트폰 앱과 웹사이트를 연계한 수업으로과학 수업의 질을 한 단계 높여라!현직 초등...,사회 정치,북랩,강동훈,12.0,"15,000원",106031498.0,0,N,2021.0
16068,17762,감정구조와 한국 사회,"아리스토텔레스부터 피에르 부르디외까지,한국 중도정치를 위한 사색을 담다정치사상사에서...",사회 정치,한울아카데미,홍성민,NaN,"56,000원",108672443.0,0,N,2022.0
1016,1023,정당과 정당 체계,“지적으로 놓칠 수 없다고 느낀 유일한 책”정당과 정당 체계에 대한 고전 중의 고전...,사회 정치,후마니타스,조반니 사르토리,198.0,"33,000원",122332035.0,0,N,2023.0
12505,13651,침몰하는 대한민국을 구하라,보수가 일어서야 대한민국이 바로 선다전쟁의 포화 속에 몸을 던져 대한민국을 구한 것...,사회 정치,따뜻한손,안상수,NaN,"15,000원",69640335.0,0,N,2019.0

In [50]:
# 장르별 데이터 개수
genre_counts = final_dataset_4['장르'].value_counts()

# 장르별 비율 계산 (전체 대비 비율)
genre_percentage = genre_counts / len(final_dataset_4) * 100

# 결과 출력
genre_percentage

장르
소설/시/희곡    55.458676
사회 정치      16.234803
에세이        15.915510
자기계발       12.391011
Name: count, dtype: float64

In [51]:
final_dataset_4.to_csv('book_1_4.csv')
book_1_4 = pd.read_csv('book_1_4.csv')
book_1_4

,Unnamed: 0,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
0,9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,"17,000원",66318782.0,1,Y,2023.0
1,11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,"13,800원",46906835.0,14,Y,2023.0
2,54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546129.0,2,Y,2023.0
3,54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546136.0,2,Y,2023.0
4,9819,58821,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,2346.0,"15,800원",59674622.0,6,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8138,43368,51121,2017년 빈곤통계연보,빈곤 및 불평등 지표는 취약계층과 사회정책 대상자의 규모 및 관련 정책의 효과성을 ...,사회 정치,한국보건사회연구원,기초보장연구실,NaN,"8,000원",60492401.0,0,N,2017.0
8139,37765,43111,스마트한 과학 수업! 1,스마트폰 앱과 웹사이트를 연계한 수업으로과학 수업의 질을 한 단계 높여라!현직 초등...,사회 정치,북랩,강동훈,12.0,"15,000원",106031498.0,0,N,2021.0
8140,16068,17762,감정구조와 한국 사회,"아리스토텔레스부터 피에르 부르디외까지,한국 중도정치를 위한 사색을 담다정치사상사에서...",사회 정치,한울아카데미,홍성민,NaN,"56,000원",108672443.0,0,N,2022.0
8141,1016,1023,정당과 정당 체계,“지적으로 놓칠 수 없다고 느낀 유일한 책”정당과 정당 체계에 대한 고전 중의 고전...,사회 정치,후마니타스,조반니 사르토리,198.0,"33,000원",122332035.0,0,N,2023.0
8142,12505,13651,침몰하는 대한민국을 구하라,보수가 일어서야 대한민국이 바로 선다전쟁의 포화 속에 몸을 던져 대한민국을 구한 것...,사회 정치,따뜻한손,안상수,NaN,"15,000원",69640335.0,0,N,2019.0

1:5

In [52]:
# 베스트 셀러 장르 비율
genre_distribution = {
    '소설/시/희곡': 60.065133,
    '에세이': 14.438399,
    '자기계발': 10.178680,
    '사회 정치': 15.317788
}

# 목표 총 개수
target_count = 8145

# 각 장르별 샘플 수 계산
samples_per_genre = {genre: int((percentage / 100) * target_count) for genre, percentage in genre_distribution.items()}

# 샘플 수가 해당 장르의 데이터 개수를 초과하지 않도록 조정
downsampled_non_bestsellers = pd.DataFrame()

for genre, num_samples in samples_per_genre.items():
    genre_data = non_bestsellers[non_bestsellers['장르'] == genre]
    if len(genre_data) < num_samples:
        num_samples = len(genre_data)  # 장르 데이터가 부족하면 전체 데이터 개수로 설정
    genre_samples = genre_data.sample(n=num_samples, replace=True)  # 필요시 중복 허용
    downsampled_non_bestsellers = pd.concat([downsampled_non_bestsellers, genre_samples])

# 최종 데이터프레임 생성
final_dataset_5 = pd.concat([bestsellers, downsampled_non_bestsellers])

# 결과 출력 및 확인
print("총 데이터 개수:", len(final_dataset_5))
final_dataset_5

총 데이터 개수: 9773

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,"17,000원",66318782.0,1,Y,2023.0
11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,"13,800원",46906835.0,14,Y,2023.0
54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546129.0,2,Y,2023.0
54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546136.0,2,Y,2023.0
9819,58821,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,2346.0,"15,800원",59674622.0,6,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
32045,36581,초등 발표 훈련,23년차 초등 학교 교사의 발표 훈련 노하우.학생들이 발표를 잘 하지 않아 걱정이 ...,사회 정치,BOOKK(부크크),김영주,276.0,"15,000원",123649348.0,0,N,2019.0
12186,13243,좀비학,『좀비학』은 ‘좀비’를 주제로 역사·과학·철학·정치·문학·문화·사회현상 등을 종횡하...,사회 정치,갈무리,김형식,NaN,"26,000원",94050793.0,0,N,2020.0
31946,36472,교육적 상상력,현행 교육 제도에 있어 평가 방법은 적절한가? 우열반 편성은 최선의 정책인 가? 성...,사회 정치,단국대학교출판부,엘리어트 아이즈너,240.0,"8,000원",62422.0,0,N,2018.0
21275,23507,구조주의와 그 이후,프랑스 현대철학의 근간인 구조주의의 탄생과 발전을 살펴본다. 이 책에서 소개하는 현...,사회 정치,살림출판사,김종우,168.0,"9,800원",2602350.0,0,N,2020.0
31027,35517,힘 있는 여성,"미투 이후, 페미니즘은 어디로 나아가야 하는가전 세계적으로 페미니즘 논쟁이 그 어느...",사회 정치,나무생각,스베냐 플라스푈러,36.0,"10,000원",64433286.0,0,N,2018.0

In [53]:
# 장르별 데이터 개수
genre_counts = final_dataset_5['장르'].value_counts()

# 장르별 비율 계산 (전체 대비 비율)
genre_percentage = genre_counts / len(final_dataset_5) * 100

# 결과 출력
genre_percentage

장르
소설/시/희곡    56.226338
사회 정치      16.074900
에세이        15.675842
자기계발       12.022920
Name: count, dtype: float64

In [54]:
final_dataset_5.to_csv('book_1_5.csv')
book_1_5 = pd.read_csv('book_1_5.csv')
book_1_5

,Unnamed: 0,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
0,9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,"17,000원",66318782.0,1,Y,2023.0
1,11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,"13,800원",46906835.0,14,Y,2023.0
2,54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546129.0,2,Y,2023.0
3,54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546136.0,2,Y,2023.0
4,9819,58821,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,2346.0,"15,800원",59674622.0,6,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9768,32045,36581,초등 발표 훈련,23년차 초등 학교 교사의 발표 훈련 노하우.학생들이 발표를 잘 하지 않아 걱정이 ...,사회 정치,BOOKK(부크크),김영주,276.0,"15,000원",123649348.0,0,N,2019.0
9769,12186,13243,좀비학,『좀비학』은 ‘좀비’를 주제로 역사·과학·철학·정치·문학·문화·사회현상 등을 종횡하...,사회 정치,갈무리,김형식,NaN,"26,000원",94050793.0,0,N,2020.0
9770,31946,36472,교육적 상상력,현행 교육 제도에 있어 평가 방법은 적절한가? 우열반 편성은 최선의 정책인 가? 성...,사회 정치,단국대학교출판부,엘리어트 아이즈너,240.0,"8,000원",62422.0,0,N,2018.0
9771,21275,23507,구조주의와 그 이후,프랑스 현대철학의 근간인 구조주의의 탄생과 발전을 살펴본다. 이 책에서 소개하는 현...,사회 정치,살림출판사,김종우,168.0,"9,800원",2602350.0,0,N,2020.0
9772,31027,35517,힘 있는 여성,"미투 이후, 페미니즘은 어디로 나아가야 하는가전 세계적으로 페미니즘 논쟁이 그 어느...",사회 정치,나무생각,스베냐 플라스푈러,36.0,"10,000원",64433286.0,0,N,2018.0

#### Pre-Processing

In [49]:
# 판매가 열에서 숫자만 추출하여 정수형으로 변환
final_dataset_3['판매가'] = final_dataset_3['판매가'].str.replace('원', '').str.replace(',', '').astype(float)
final_dataset_3

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,17000.0,66318782.0,1,Y,2023.0
11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,13800.0,46906835.0,14,Y,2023.0
54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,15800.0,65546129.0,2,Y,2023.0
54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,15800.0,65546136.0,2,Y,2023.0
9819,58821,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,2346.0,15800.0,59674622.0,6,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
28672,32917,한국가정과 다문화가정 내 배우자 폭력의 유형 및 특성 비교 연구,한국가정과 다문화가정 내 배우자 폭력의 유형 및 특성 비교 연구일반적으로 배우자 폭...,사회 정치,집문당,그레이스 정,12.0,13000.0,90334722.0,0,N,2020.0
32554,37127,특수교사119,"“교사의 노력과 고민만큼 학생이 성장한다.”수업은 기본이고 생활습관지도, 진로직업지...",사회 정치,에듀니티,원재연,1392.0,19800.0,89958290.0,0,N,2017.0
43320,51029,스마트융합 환경에서의 박물관 미술관 기능개선의 방향 연구,이 책은 한국문화관광연구원의 스마트융합 환경에서의 박물관 미술관 기능개선의 방향 연...,사회 정치,한국문화관광연구원,류정아,NaN,9000.0,64484555.0,0,N,2017.0
49677,61844,한국의 전투와 무기,"이 책은 우리 역사에서 중요한 전투를 골라 전투의 원인과 경과 및 결과, 전투에 참...",사회 정치,현암사,신현득,12.0,15000.0,2943994.0,0,N,2020.0
48827,60788,전쟁과 경영,세계에서 가장 크고 강한 조직인 미국 육군의 변혁을성공으로 이끈 지도자들의 생생한 ...,사회 정치,지식노마드,고든 R. 설리번,NaN,18900.0,76106872.0,0,N,2018.0

In [50]:
# 필요한 컬럼 선택
final_dataset_3 = final_dataset_3[["도서 이름", "줄거리", "장르", "출판사", "작가", "판매가", "best"]]

# 결과 출력
final_dataset_3

,도서 이름,줄거리,장르,출판사,작가,판매가,best
9847,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,17000.0,Y
11831,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,13800.0,Y
54459,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y
54458,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y
9819,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,15800.0,Y
...,...,...,...,...,...,...,...
28672,한국가정과 다문화가정 내 배우자 폭력의 유형 및 특성 비교 연구,한국가정과 다문화가정 내 배우자 폭력의 유형 및 특성 비교 연구일반적으로 배우자 폭...,사회 정치,집문당,그레이스 정,13000.0,N
32554,특수교사119,"“교사의 노력과 고민만큼 학생이 성장한다.”수업은 기본이고 생활습관지도, 진로직업지...",사회 정치,에듀니티,원재연,19800.0,N
43320,스마트융합 환경에서의 박물관 미술관 기능개선의 방향 연구,이 책은 한국문화관광연구원의 스마트융합 환경에서의 박물관 미술관 기능개선의 방향 연...,사회 정치,한국문화관광연구원,류정아,9000.0,N
49677,한국의 전투와 무기,"이 책은 우리 역사에서 중요한 전투를 골라 전투의 원인과 경과 및 결과, 전투에 참...",사회 정치,현암사,신현득,15000.0,N
48827,전쟁과 경영,세계에서 가장 크고 강한 조직인 미국 육군의 변혁을성공으로 이끈 지도자들의 생생한 ...,사회 정치,지식노마드,고든 R. 설리번,18900.0,N

In [51]:
import pandas as pd

final_dataset_3 = pd.read_csv('book_1_3_samegenre.csv')
len(final_dataset_3['작가'].unique())

5145

In [65]:
final_dataset_4.to_csv('book_1_4.csv', index=False)
book_1_4 = pd.read_csv('book_1_4.csv')
book_1_4

,도서 이름,줄거리,장르,출판사,작가,판매가,best
0,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,17000.0,Y
1,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,13800.0,Y
2,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y
3,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y
4,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,15800.0,Y
...,...,...,...,...,...,...,...
8138,2017년 빈곤통계연보,빈곤 및 불평등 지표는 취약계층과 사회정책 대상자의 규모 및 관련 정책의 효과성을 ...,사회 정치,한국보건사회연구원,기초보장연구실,8000.0,N
8139,스마트한 과학 수업! 1,스마트폰 앱과 웹사이트를 연계한 수업으로과학 수업의 질을 한 단계 높여라!현직 초등...,사회 정치,북랩,강동훈,15000.0,N
8140,감정구조와 한국 사회,"아리스토텔레스부터 피에르 부르디외까지,한국 중도정치를 위한 사색을 담다정치사상사에서...",사회 정치,한울아카데미,홍성민,56000.0,N
8141,정당과 정당 체계,“지적으로 놓칠 수 없다고 느낀 유일한 책”정당과 정당 체계에 대한 고전 중의 고전...,사회 정치,후마니타스,조반니 사르토리,33000.0,N
8142,침몰하는 대한민국을 구하라,보수가 일어서야 대한민국이 바로 선다전쟁의 포화 속에 몸을 던져 대한민국을 구한 것...,사회 정치,따뜻한손,안상수,15000.0,N